#!/bin/bash
set -e

echo "=== Spotify → Soulseek Downloader ==="
echo ""

# Detect docker compose command (v2 plugin vs v1 standalone)
if docker compose version > /dev/null 2>&1; then
    COMPOSE="docker compose"
elif docker-compose version > /dev/null 2>&1; then
    COMPOSE="docker-compose"
else
    echo "ERROR: Neither 'docker compose' nor 'docker-compose' found."
    echo "Please install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

# Check if Docker/OrbStack is running
if ! docker info > /dev/null 2>&1; then
    echo "ERROR: Docker is not running."
    echo "Please start Docker Desktop or OrbStack first."
    exit 1
fi

# Check for port conflicts
for port in 8000 5030; do
    if lsof -i ":$port" -sTCP:LISTEN > /dev/null 2>&1; then
        echo "ERROR: Port $port is already in use."
        echo "Please stop the service using that port, or change it in docker-compose.yml."
        exit 1
    fi
done

# Check .env file
if [ ! -f .env ]; then
    echo "No .env file found. Creating from template..."
    cp .env.example .env

    # Auto-generate a random API key
    RANDOM_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '/+=')
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "s/supersecretapikey123change_me/$RANDOM_KEY/" .env
    else
        sed -i "s/supersecretapikey123change_me/$RANDOM_KEY/" .env
    fi

    echo ""
    echo "Please edit .env with your credentials:"
    echo "  1. Soulseek username/password (https://www.slsknet.org/)"
    echo "  2. Spotify Client ID/Secret (https://developer.spotify.com/dashboard)"
    echo ""
    echo "Then run this script again."
    exit 1
fi

# Validate that placeholder values have been replaced
source .env
if [ "$SLSKD_SLSK_USERNAME" = "your_soulseek_username" ] || [ -z "$SLSKD_SLSK_USERNAME" ]; then
    echo "ERROR: Please set your Soulseek credentials in .env"
    echo "  Register at https://www.slsknet.org/ (free)"
    exit 1
fi
if [ "$SPOTIFY_CLIENT_ID" = "your_spotify_client_id" ] || [ -z "$SPOTIFY_CLIENT_ID" ]; then
    echo "ERROR: Please set your Spotify API credentials in .env"
    echo "  Create an app at https://developer.spotify.com/dashboard"
    exit 1
fi

# Auto-generate API key if user still has the default placeholder
if [ "$SLSKD_API_KEY" = "supersecretapikey123change_me" ]; then
    RANDOM_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '/+=')
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "s/supersecretapikey123change_me/$RANDOM_KEY/" .env
    else
        sed -i "s/supersecretapikey123change_me/$RANDOM_KEY/" .env
    fi
    # Re-source so the new key is visible to the rest of this script.
    SLSKD_API_KEY="$RANDOM_KEY"
    echo "Generated random API key for slskd."
fi

# Create directories
mkdir -p downloads slskd-data shared music

# Sync the slskd API key into slskd.yml.
#
# Why this exists: slskd's env-var config binding does NOT create new entries
# in the api_keys dictionary (a known limitation of .NET configuration with
# Dictionary<string, T> types). Setting SLSKD_WEB_AUTHENTICATION__API_KEYS__
# SPOTASOUL__KEY etc. via docker-compose looks right but is silently dropped,
# causing slskd to reject the backend's requests with "Unknown API key
# beginning with: ...".
#
# The fix is to write the api_keys section directly into slskd.yml, which
# slskd loads reliably on startup. We use a BEGIN/END marker block so this
# script can update the key idempotently without destroying any other
# user-added config in the same file.
SLSKD_YML="slskd-data/slskd.yml"
MARKER_BEGIN="# BEGIN managed-by: spslsk-start.sh"
MARKER_END="# END managed-by: spslsk-start.sh"

MANAGED_BLOCK=$(cat <<EOF
${MARKER_BEGIN}
# This block is regenerated by start.sh from SLSKD_API_KEY in .env on every
# run. Do not edit by hand — edit .env and re-run start.sh instead.
# Anything outside the BEGIN/END markers is preserved.
web:
  authentication:
    api_keys:
      spotasoul:
        key: ${SLSKD_API_KEY}
        role: readwrite
        cidr: 0.0.0.0/0,::/0
${MARKER_END}
EOF
)

if [ ! -f "$SLSKD_YML" ]; then
    # Fresh install — create a minimal file with just our block.
    echo "$MANAGED_BLOCK" > "$SLSKD_YML"
    echo "Created $SLSKD_YML with slskd API key."
elif grep -qF "$MARKER_BEGIN" "$SLSKD_YML"; then
    # Managed block already present — replace it in place using awk so we
    # don't need a tempfile dance with line anchors that would be fragile
    # across BSD/GNU sed differences.
    awk -v begin="$MARKER_BEGIN" -v end="$MARKER_END" -v block="$MANAGED_BLOCK" '
        BEGIN {in_block = 0; printed = 0}
        index($0, begin) {in_block = 1; if (!printed) {print block; printed = 1}; next}
        index($0, end) {in_block = 0; next}
        !in_block {print}
    ' "$SLSKD_YML" > "$SLSKD_YML.tmp" && mv "$SLSKD_YML.tmp" "$SLSKD_YML"
    echo "Updated slskd API key in $SLSKD_YML."
else
    # No managed block yet — prepend one, preserving existing contents.
    (echo "$MANAGED_BLOCK"; echo; cat "$SLSKD_YML") > "$SLSKD_YML.tmp" && mv "$SLSKD_YML.tmp" "$SLSKD_YML"
    echo "Added managed block to $SLSKD_YML."
fi

echo "Starting services..."
$COMPOSE up --build -d

echo ""
echo "Waiting for services to start..."
sleep 5

echo ""

# Start host-side helper for native file manager access (port 8001)
HELPER_PID=""
cleanup() {
    if [ -n "$HELPER_PID" ]; then
        kill "$HELPER_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT

# Detect OS for the "open folder" command
if [ "$(uname)" = "Darwin" ]; then
    OPEN_CMD="open"
elif command -v xdg-open > /dev/null 2>&1; then
    OPEN_CMD="xdg-open"
else
    OPEN_CMD=""
fi

if [ -n "$OPEN_CMD" ]; then
    python3 -c "
import http.server, subprocess, json, os

OPEN_CMD = '$OPEN_CMD'

class Handler(http.server.BaseHTTPRequestHandler):
    def do_POST(self):
        if self.path == '/open-folder':
            folder = os.path.join(os.getcwd(), 'downloads')
            # Check for subfolder in request body
            try:
                length = int(self.headers.get('Content-Length', 0))
                if length > 0:
                    body = json.loads(self.rfile.read(length))
                    sub = body.get('subfolder', '')
                    if sub:
                        # Try exact match first, then sanitized
                        candidate = os.path.join(folder, sub)
                        if not os.path.isdir(candidate):
                            safe = sub.replace('/', '').replace('..', '')[:100]
                            candidate = os.path.join(folder, safe)
                        if os.path.isdir(candidate):
                            folder = candidate
            except Exception:
                pass
            os.makedirs(folder, exist_ok=True)
            subprocess.Popen([OPEN_CMD, folder])
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(json.dumps({'ok': True}).encode())
        else:
            self.send_response(404)
            self.end_headers()
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()
    def log_message(self, *args):
        pass  # Suppress logs

http.server.HTTPServer(('127.0.0.1', 8001), Handler).serve_forever()
" &
    HELPER_PID=$!
fi

echo "=== Ready! ==="
echo "  App:   http://localhost:8000"
echo "  slskd: http://localhost:5030 (user: slskd / pass: slskd)"
echo ""
echo "To stop: Ctrl+C or $COMPOSE down"

# Wait for Docker containers (keeps script running so Ctrl+C stops everything)
$COMPOSE logs -f
