#!/bin/bash
set -e

echo "=== Spotify → Soulseek Downloader ==="
echo ""

# Every path below (slskd-data, downloads, the compose file) is relative to
# the project root, so anchor there instead of trusting the caller's cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Probe the folder helper without depending on curl being installed —
# python3 is already a hard requirement for running the helper itself.
helper_alive() {
    python3 - <<'PY' > /dev/null 2>&1
import sys, urllib.request
try:
    urllib.request.urlopen("http://127.0.0.1:8001/health", timeout=1).read()
except Exception:
    sys.exit(1)
PY
}

# Detect docker compose command (v2 plugin vs v1 standalone)
if docker compose version > /dev/null 2>&1; then
    COMPOSE="docker compose"
elif docker-compose version > /dev/null 2>&1; then
    COMPOSE="docker-compose"
else
    echo "ERROR: Neither 'docker compose' nor 'docker-compose' found."
    echo "Please install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

# Check if Docker/OrbStack is running
if ! docker info > /dev/null 2>&1; then
    echo "ERROR: Docker is not running."
    echo "Please start Docker Desktop or OrbStack first."
    exit 1
fi

# Check for port conflicts
for port in 8000 5030; do
    if lsof -i ":$port" -sTCP:LISTEN > /dev/null 2>&1; then
        echo "ERROR: Port $port is already in use."
        echo "Please stop the service using that port, or change it in docker-compose.yml."
        exit 1
    fi
done

# Check .env file
if [ ! -f .env ]; then
    echo "No .env file found. Creating from template..."
    cp .env.example .env

    # Auto-generate a random API key
    RANDOM_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '/+=')
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "s/supersecretapikey123change_me/$RANDOM_KEY/" .env
    else
        sed -i "s/supersecretapikey123change_me/$RANDOM_KEY/" .env
    fi

    echo ""
    echo "Please edit .env with your credentials:"
    echo "  1. Soulseek username/password (https://www.slsknet.org/)"
    echo "  2. Spotify Client ID/Secret (https://developer.spotify.com/dashboard)"
    echo ""
    echo "Then run this script again."
    exit 1
fi

# Validate that placeholder values have been replaced
source .env
if [ "$SLSKD_SLSK_USERNAME" = "your_soulseek_username" ] || [ -z "$SLSKD_SLSK_USERNAME" ]; then
    echo "ERROR: Please set your Soulseek credentials in .env"
    echo "  Register at https://www.slsknet.org/ (free)"
    exit 1
fi
if [ "$SPOTIFY_CLIENT_ID" = "your_spotify_client_id" ] || [ -z "$SPOTIFY_CLIENT_ID" ]; then
    echo "ERROR: Please set your Spotify API credentials in .env"
    echo "  Create an app at https://developer.spotify.com/dashboard"
    exit 1
fi

# Auto-generate API key if user still has the default placeholder
if [ "$SLSKD_API_KEY" = "supersecretapikey123change_me" ]; then
    RANDOM_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '/+=')
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "s/supersecretapikey123change_me/$RANDOM_KEY/" .env
    else
        sed -i "s/supersecretapikey123change_me/$RANDOM_KEY/" .env
    fi
    # Re-source so the new key is visible to the rest of this script.
    SLSKD_API_KEY="$RANDOM_KEY"
    echo "Generated random API key for slskd."
fi

# Create directories
mkdir -p downloads slskd-data shared music

# Sync the slskd API key into slskd.yml.
#
# Why this exists: slskd's env-var config binding does NOT create new entries
# in the api_keys dictionary (a known limitation of .NET configuration with
# Dictionary<string, T> types). Setting SLSKD_WEB_AUTHENTICATION__API_KEYS__
# SPOTASOUL__KEY etc. via docker-compose looks right but is silently dropped,
# causing slskd to reject the backend's requests with "Unknown API key
# beginning with: ...".
#
# The fix is to write the api_keys section directly into slskd.yml, which
# slskd loads reliably on startup. We use a BEGIN/END marker block so this
# script can update the key idempotently without destroying any other
# user-added config in the same file.
SLSKD_YML="slskd-data/slskd.yml"
MARKER_BEGIN="# BEGIN managed-by: spslsk-start.sh"
MARKER_END="# END managed-by: spslsk-start.sh"

MANAGED_BLOCK=$(cat <<EOF
${MARKER_BEGIN}
# This block is regenerated by start.sh from SLSKD_API_KEY in .env on every
# run. Do not edit by hand — edit .env and re-run start.sh instead.
# Anything outside the BEGIN/END markers is preserved.
web:
  authentication:
    api_keys:
      spotasoul:
        key: ${SLSKD_API_KEY}
        role: readwrite
        cidr: 0.0.0.0/0,::/0
${MARKER_END}
EOF
)

if [ ! -f "$SLSKD_YML" ]; then
    # Fresh install — create a minimal file with just our block.
    echo "$MANAGED_BLOCK" > "$SLSKD_YML"
    echo "Created $SLSKD_YML with slskd API key."
else
    # Strip any existing managed block, then prepend a fresh one. We
    # always rewrite rather than patch in place so the logic is the same
    # whether the block exists yet or not, and it avoids BSD-vs-GNU sed/awk
    # portability traps. The sed address range uses escaped '.' so the
    # literal '.sh' in the marker doesn't act as a regex metachar.
    MARKER_BEGIN_RE="# BEGIN managed-by: spslsk-start\.sh"
    MARKER_END_RE="# END managed-by: spslsk-start\.sh"
    sed "/$MARKER_BEGIN_RE/,/$MARKER_END_RE/d" "$SLSKD_YML" > "$SLSKD_YML.tmp"
    (echo "$MANAGED_BLOCK"; echo; cat "$SLSKD_YML.tmp") > "$SLSKD_YML"
    rm -f "$SLSKD_YML.tmp"
    echo "Synced slskd API key into $SLSKD_YML."
fi

echo "Starting services..."
# HOST_DOWNLOADS_DIR tells the backend the real host path of ./downloads so
# the UI can display and copy a path the user can actually paste into Finder
# — inside the container it only ever sees /app/downloads.
export HOST_DOWNLOADS_DIR="$(pwd)/downloads"
$COMPOSE up --build -d

echo ""
echo "Waiting for services to start..."
sleep 5

echo ""

# Start host-side helper for native file manager access (port 8001)
HELPER_PID=""
cleanup() {
    if [ -n "$HELPER_PID" ]; then
        kill "$HELPER_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT

# The helper lives in host_helper.py (not inlined here) so it can be read,
# tested, and run standalone. Port 8001 may already be held by a helper from
# a previous run that outlived its shell — reuse it instead of dying on
# "address already in use", which used to leave the UI with no opener at all.
if helper_alive; then
    echo "Folder helper already running on :8001 — reusing it."
elif [ -f "$SCRIPT_DIR/host_helper.py" ]; then
    python3 "$SCRIPT_DIR/host_helper.py" --downloads "$SCRIPT_DIR/downloads" --port 8001 &
    HELPER_PID=$!
    # Give it a moment to bind, then report honestly whether it came up.
    sleep 1
    if helper_alive; then
        echo "Folder helper running on :8001 (\"Open folder\" buttons active)."
    else
        echo "WARNING: folder helper failed to start — the UI will fall back"
        echo "         to copying the downloads path to your clipboard."
        HELPER_PID=""
    fi
else
    echo "WARNING: host_helper.py not found — \"Open folder\" will fall back to"
    echo "         copying the path to your clipboard."
fi

echo "=== Ready! ==="
echo "  App:       http://localhost:8000"
echo "  slskd:     http://localhost:5030 (user: slskd / pass: slskd)"
echo "  Downloads: $HOST_DOWNLOADS_DIR"
echo ""
echo "To stop: Ctrl+C or $COMPOSE down"

# Wait for Docker containers (keeps script running so Ctrl+C stops everything)
$COMPOSE logs -f
